imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: sonata.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

doctrine_mongodb:
    connections:
        default:
            server: "%default_server%"
            options: {}
    default_database: "%default_database%"
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: "%mailer_encryption%"
    auth_mode:  "%mailer_auth_mode%"
    sender_address: "%mailer_user%"
    spool:
        type: file
        path: "%kernel.root_dir%/../var/spool"

fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: FDevs\TeamBundle\Model\User
    group:
        group_class: FDevs\TeamBundle\Model\Group

f_devs_tag:
    list_type:
        skill: 'Skill'

f_devs_block:
    predefined_blocks:
        about_left:
            label: 'About Left'
            template: 'FDevsCoreBundle:Block:about.html.twig'
        about_right:
            label: 'About Right'
            template: 'FDevsCoreBundle:Block:about.html.twig'
        about_freelancer:
            label: 'About Freelancer'
            template: 'FDevsCoreBundle:Block:footer.html.twig'
        location:
            label: 'Location'
            template: 'FDevsCoreBundle:Block:footer.html.twig'

f_devs_file:
    default: 'local'
    filesystems:
        local:
            web_path: "http://%domain%/uploads/image/"
            validation_options:
                accept_file_types: '/(\.|\/)(gif|jpe?g|png)$/i'
            thumbs:
                small: {height: 100, width: 100}
            gaufrette_filesystem: 'base'
        team:
            web_path: "http://%domain%/uploads/team/"
            validation_options:
                accept_file_types: '/(\.|\/)(gif|jpe?g|png)$/i'
            thumbs:
                small: {height: 225, width: 225}
            gaufrette_filesystem: 'team'
        catalog:
            web_path: "http://%domain%/uploads/catalog/"
            validation_options:
                accept_file_types: '/(\.|\/)(gif|jpe?g|png)$/i'
            thumbs:
                small: {height: 289, width: 400}
                prewiew: {height: 450, width: 600}
            gaufrette_filesystem: 'catalog'

knp_gaufrette:
    adapters:
        base:
            local:
                directory: "%kernel.root_dir%/../web/uploads/image/"
        team:
            local:
                directory: "%kernel.root_dir%/../web/uploads/team/"
        catalog:
            local:
                directory: "%kernel.root_dir%/../web/uploads/catalog/"
    filesystems:
        base:
            adapter: base
        team:
            adapter: team
        catalog:
            adapter: catalog

f_devs_contact_us:
    db_driver: 'mongodb'
    emails: ['andrey@4devs.org','victor@4devs.org']
    from: "%mailer_user%"
    admin_service: 'sonata'

f_devs_catalog:
    item_types:
        portfolio: 'portfolio'
        our_own_projects: 'Our own projects'
        open_source: 'Open source'

lunetics_locale:
    strict_mode: true
    allowed_locales: %allowed.locales%
    guessing_order:
        - router
        - browser
        - session
        - cookie
        - query
    switcher:
        template: FDevsCoreBundle:Switcher:switcher_links.html.twig

twitter_bootstrap:
    assets:
        stylesheets:
            - bundles/fdevscore/css/bootstrap.min.css
            - bundles/fdevscore/css/freelancer.css
            - bundles/fdevscore/font-awesome-4.1.0/css/font-awesome.min.css
            - //fonts.googleapis.com/css?family=Montserrat:400,700
            - //fonts.googleapis.com/css?family=Montserrat:400,700
            - //fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic
        javascripts:
            - bundles/fdevscore/js/jquery-1.11.0.js
            - bundles/fdevscore/js/bootstrap.min.js
            - //cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js
            - bundles/fdevscore/js/classie.js
            - bundles/fdevscore/js/cbpAnimatedHeader.js
            - bundles/fdevscore/js/freelancer.js
            - bundles/fdevscontactus/js/jqBootstrapValidation.js
            - bundles/fdevscontactus/js/contact_me.js
